version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Syncing files to S3..."
      - aws s3 sync . s3://$S3_BUCKET --delete --exclude ".git/*" --exclude "buildspec.yml" --exclude "README.md" --exclude ".gitignore"
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - '**/*'